# Dependencies
markdown:	kramdown
# Permalinks
permalink: /:year/:month/:day/:title

# Setup
title:            Daniele Esposti's Blog
# tagline:          'blog'
description:      'My personal blog.'
url:              http://localhost:4000
baseurl:
commentsystem:    disqus
disqus:           expobrain

# author:
#   name:           Ian Brunelli
#   url:            https://google.com/+IanCamporezBrunelli

paginate:         5
gems:
- jekyll-paginate
- jekyll-sitemap

# Custom vars
icon:             /assets/images/profile.jpg
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/expobrain
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/expobrain
    desc:         Fork me on github

  - icon:         linkedin
    url:          https://www.linkedin.com/in/danieleesposti
    desc:         Look at me on linkedin

  # - icon:         googleplus-alt
  #   url:          https://google.com/+IanCamporezBrunelli
  #   desc:         Add me on google+

  # - icon:         feed
  #   url:          http://camporez.github.io/atom.xml
  #   desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

# copyright:
#   author:         Camporez
#   url:            http://camporez.github.io
#   type_title:     Some rights reserved
#   type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-423458-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
